import Head from 'next/head';
import { Range } from '@/components/range/Range';

export default function Home() {
  return (
    <>
      <Head>
        <title>Range App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Range App</h1>

        <br />
        <br />
        <br />

        <Range min={0} max={100} defaultValue={[30, 80]} unit="€" />
        <br />
        <br />
        <Range min={0} max={100} unit="€" />
        <br />
        <br />
        {/*<Range min={5.99} max={70} unit="€" />*/}
      </main>
    </>
  );
}
