import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Range App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Range App</h1>

        <Link href="/exercise1">
          <h2>Normal Range</h2>
        </Link>
        <Link href="/exercise2">
          <h2>Fixed values range</h2>
        </Link>
      </main>
    </>
  );
}
